# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 735)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 540))
        MainWindow.setMaximumSize(QtCore.QSize(4096, 2160))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.layout_main = QtWidgets.QWidget(MainWindow)
        self.layout_main.setMinimumSize(QtCore.QSize(1024, 540))
        self.layout_main.setMaximumSize(QtCore.QSize(4096, 2160))
        self.layout_main.setAutoFillBackground(False)
        self.layout_main.setStyleSheet("QWidget{\n"
"    background: white\n"
"}")
        self.layout_main.setObjectName("layout_main")
        self.gridLayout = QtWidgets.QGridLayout(self.layout_main)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 5)
        self.layout_robopoly = QtWidgets.QHBoxLayout()
        self.layout_robopoly.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layout_robopoly.setSpacing(6)
        self.layout_robopoly.setObjectName("layout_robopoly")
        self.robopoly = QtWidgets.QLabel(self.layout_main)
        self.robopoly.setEnabled(True)
        self.robopoly.setMinimumSize(QtCore.QSize(1000, 180))
        self.robopoly.setMaximumSize(QtCore.QSize(1920, 360))
        self.robopoly.setText("")
        self.robopoly.setPixmap(QtGui.QPixmap("logos/logo_gc.png"))
        self.robopoly.setScaledContents(True)
        self.robopoly.setWordWrap(False)
        self.robopoly.setOpenExternalLinks(False)
        self.robopoly.setObjectName("robopoly")
        self.layout_robopoly.addWidget(self.robopoly)
        self.gridLayout.addLayout(self.layout_robopoly, 0, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.layout_main)
        self.line.setStyleSheet("border: none;\n"
"background: gray;")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layout_main)
        self.line_2.setStyleSheet("border: none;\n"
"background: gray;")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 3, 1, 1)
        self.layout_gym = QtWidgets.QVBoxLayout()
        self.layout_gym.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layout_gym.setSpacing(6)
        self.layout_gym.setObjectName("layout_gym")
        self.label_gym = QtWidgets.QLabel(self.layout_main)
        self.label_gym.setMaximumSize(QtCore.QSize(1300, 390))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_gym.setFont(font)
        self.label_gym.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gym.setObjectName("label_gym")
        self.layout_gym.addWidget(self.label_gym)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_gym.addItem(spacerItem1)
        self.label_time_gym = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_time_gym.setFont(font)
        self.label_time_gym.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_gym.setObjectName("label_time_gym")
        self.layout_gym.addWidget(self.label_time_gym)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_gym.addItem(spacerItem2)
        self.layout_infos_gym = QtWidgets.QGridLayout()
        self.layout_infos_gym.setContentsMargins(70, -1, 70, -1)
        self.layout_infos_gym.setSpacing(6)
        self.layout_infos_gym.setObjectName("layout_infos_gym")
        self.label_team_gym = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_team_gym.setFont(font)
        self.label_team_gym.setObjectName("label_team_gym")
        self.layout_infos_gym.addWidget(self.label_team_gym, 0, 0, 1, 1)
        self.label_score_gym = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_score_gym.setFont(font)
        self.label_score_gym.setObjectName("label_score_gym")
        self.layout_infos_gym.addWidget(self.label_score_gym, 2, 0, 1, 1)
        self.name_team_gym = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_team_gym.setFont(font)
        self.name_team_gym.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_team_gym.setObjectName("name_team_gym")
        self.layout_infos_gym.addWidget(self.name_team_gym, 0, 1, 1, 1)
        self.nb_points_gym = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.nb_points_gym.setFont(font)
        self.nb_points_gym.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nb_points_gym.setObjectName("nb_points_gym")
        self.layout_infos_gym.addWidget(self.nb_points_gym, 2, 1, 1, 1)
        self.layout_gym.addLayout(self.layout_infos_gym)
        self.gridLayout.addLayout(self.layout_gym, 4, 4, 1, 1)
        self.label_ski_2 = QtWidgets.QLabel(self.layout_main)
        self.label_ski_2.setMinimumSize(QtCore.QSize(400, 30))
        self.label_ski_2.setMaximumSize(QtCore.QSize(4096, 390))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ski_2.setFont(font)
        self.label_ski_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ski_2.setObjectName("label_ski_2")
        self.gridLayout.addWidget(self.label_ski_2, 7, 0, 1, 5)
        self.layout_sponsors_2 = QtWidgets.QHBoxLayout()
        self.layout_sponsors_2.setSpacing(6)
        self.layout_sponsors_2.setObjectName("layout_sponsors_2")
        self.label = QtWidgets.QLabel(self.layout_main)
        self.label.setMaximumSize(QtCore.QSize(300, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logos/agepoly.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layout_sponsors_2.addWidget(self.label)
        self.makita = QtWidgets.QLabel(self.layout_main)
        self.makita.setMaximumSize(QtCore.QSize(260, 80))
        self.makita.setText("")
        self.makita.setPixmap(QtGui.QPixmap("logos/makita.png"))
        self.makita.setScaledContents(True)
        self.makita.setObjectName("makita")
        self.layout_sponsors_2.addWidget(self.makita)
        self._3dprintnewtechno = QtWidgets.QLabel(self.layout_main)
        self._3dprintnewtechno.setMaximumSize(QtCore.QSize(123, 100))
        self._3dprintnewtechno.setText("")
        self._3dprintnewtechno.setPixmap(QtGui.QPixmap("logos/3dprintnewtechno.jpg"))
        self._3dprintnewtechno.setScaledContents(True)
        self._3dprintnewtechno.setObjectName("_3dprintnewtechno")
        self.layout_sponsors_2.addWidget(self._3dprintnewtechno)
        self.wurth = QtWidgets.QLabel(self.layout_main)
        self.wurth.setMaximumSize(QtCore.QSize(200, 80))
        self.wurth.setText("")
        self.wurth.setPixmap(QtGui.QPixmap("logos/würth.png"))
        self.wurth.setScaledContents(True)
        self.wurth.setObjectName("wurth")
        self.layout_sponsors_2.addWidget(self.wurth)
        self.gridLayout.addLayout(self.layout_sponsors_2, 9, 0, 1, 5)
        self.layout_timer_tchoukball = QtWidgets.QHBoxLayout()
        self.layout_timer_tchoukball.setSpacing(6)
        self.layout_timer_tchoukball.setObjectName("layout_timer_tchoukball")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_timer_tchoukball.addItem(spacerItem3)
        self.lcd_general_min = QtWidgets.QLCDNumber(self.layout_main)
        self.lcd_general_min.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcd_general_min.setFont(font)
        self.lcd_general_min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_general_min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_general_min.setDigitCount(1)
        self.lcd_general_min.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_general_min.setObjectName("lcd_general_min")
        self.layout_timer_tchoukball.addWidget(self.lcd_general_min)
        self.label_5 = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.layout_timer_tchoukball.addWidget(self.label_5)
        self.lcd_general_sec = QtWidgets.QLCDNumber(self.layout_main)
        self.lcd_general_sec.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcd_general_sec.setFont(font)
        self.lcd_general_sec.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_general_sec.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_general_sec.setDigitCount(2)
        self.lcd_general_sec.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_general_sec.setObjectName("lcd_general_sec")
        self.layout_timer_tchoukball.addWidget(self.lcd_general_sec)
        self.label_6 = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.layout_timer_tchoukball.addWidget(self.label_6)
        self.lcd_general_millis = QtWidgets.QLCDNumber(self.layout_main)
        self.lcd_general_millis.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcd_general_millis.setFont(font)
        self.lcd_general_millis.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_general_millis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_general_millis.setDigitCount(2)
        self.lcd_general_millis.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_general_millis.setObjectName("lcd_general_millis")
        self.layout_timer_tchoukball.addWidget(self.lcd_general_millis)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_timer_tchoukball.addItem(spacerItem4)
        self.gridLayout.addLayout(self.layout_timer_tchoukball, 2, 0, 1, 5)
        self.layout_ski = QtWidgets.QVBoxLayout()
        self.layout_ski.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_ski.setSpacing(6)
        self.layout_ski.setObjectName("layout_ski")
        self.label_ski = QtWidgets.QLabel(self.layout_main)
        self.label_ski.setMinimumSize(QtCore.QSize(100, 30))
        self.label_ski.setMaximumSize(QtCore.QSize(1300, 390))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ski.setFont(font)
        self.label_ski.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ski.setObjectName("label_ski")
        self.layout_ski.addWidget(self.label_ski)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_ski.addItem(spacerItem5)
        self.label_time_ski = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_time_ski.setFont(font)
        self.label_time_ski.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_ski.setObjectName("label_time_ski")
        self.layout_ski.addWidget(self.label_time_ski)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_ski.addItem(spacerItem6)
        self.layout_infos_ski = QtWidgets.QGridLayout()
        self.layout_infos_ski.setContentsMargins(70, -1, 70, -1)
        self.layout_infos_ski.setSpacing(6)
        self.layout_infos_ski.setObjectName("layout_infos_ski")
        self.label_team_ski = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_team_ski.setFont(font)
        self.label_team_ski.setObjectName("label_team_ski")
        self.layout_infos_ski.addWidget(self.label_team_ski, 0, 0, 1, 1)
        self.label_score_ski = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_score_ski.setFont(font)
        self.label_score_ski.setObjectName("label_score_ski")
        self.layout_infos_ski.addWidget(self.label_score_ski, 2, 0, 1, 1)
        self.name_team_ski = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_team_ski.setFont(font)
        self.name_team_ski.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_team_ski.setObjectName("name_team_ski")
        self.layout_infos_ski.addWidget(self.name_team_ski, 0, 1, 1, 1)
        self.nb_points_ski = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.nb_points_ski.setFont(font)
        self.nb_points_ski.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nb_points_ski.setObjectName("nb_points_ski")
        self.layout_infos_ski.addWidget(self.nb_points_ski, 2, 1, 1, 1)
        self.layout_ski.addLayout(self.layout_infos_ski)
        self.gridLayout.addLayout(self.layout_ski, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.epfl = QtWidgets.QLabel(self.layout_main)
        self.epfl.setMaximumSize(QtCore.QSize(200, 87))
        self.epfl.setText("")
        self.epfl.setPixmap(QtGui.QPixmap("logos/epfl.png"))
        self.epfl.setScaledContents(True)
        self.epfl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.epfl.setObjectName("epfl")
        self.horizontalLayout.addWidget(self.epfl)
        self.logitech = QtWidgets.QLabel(self.layout_main)
        self.logitech.setMinimumSize(QtCore.QSize(157, 50))
        self.logitech.setMaximumSize(QtCore.QSize(200, 75))
        self.logitech.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logitech.setText("")
        self.logitech.setPixmap(QtGui.QPixmap("logos/logitech.png"))
        self.logitech.setScaledContents(True)
        self.logitech.setAlignment(QtCore.Qt.AlignCenter)
        self.logitech.setObjectName("logitech")
        self.horizontalLayout.addWidget(self.logitech)
        self.faulhaber = QtWidgets.QLabel(self.layout_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faulhaber.sizePolicy().hasHeightForWidth())
        self.faulhaber.setSizePolicy(sizePolicy)
        self.faulhaber.setMinimumSize(QtCore.QSize(400, 30))
        self.faulhaber.setMaximumSize(QtCore.QSize(600, 50))
        self.faulhaber.setAutoFillBackground(False)
        self.faulhaber.setStyleSheet("")
        self.faulhaber.setText("")
        self.faulhaber.setPixmap(QtGui.QPixmap("logos/faulhaber.png"))
        self.faulhaber.setScaledContents(True)
        self.faulhaber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.faulhaber.setObjectName("faulhaber")
        self.horizontalLayout.addWidget(self.faulhaber)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 6, 0, 1, 5)
        self.layout_tchoukball = QtWidgets.QVBoxLayout()
        self.layout_tchoukball.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_tchoukball.setSpacing(6)
        self.layout_tchoukball.setObjectName("layout_tchoukball")
        self.label_tchoukball = QtWidgets.QLabel(self.layout_main)
        self.label_tchoukball.setMaximumSize(QtCore.QSize(1300, 390))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_tchoukball.setFont(font)
        self.label_tchoukball.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tchoukball.setObjectName("label_tchoukball")
        self.layout_tchoukball.addWidget(self.label_tchoukball)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_tchoukball.addItem(spacerItem8)
        self.label_time_tchoukball = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_time_tchoukball.setFont(font)
        self.label_time_tchoukball.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_tchoukball.setObjectName("label_time_tchoukball")
        self.layout_tchoukball.addWidget(self.label_time_tchoukball)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_tchoukball.addItem(spacerItem9)
        self.layout_infos_tchoukball = QtWidgets.QGridLayout()
        self.layout_infos_tchoukball.setContentsMargins(70, -1, 70, -1)
        self.layout_infos_tchoukball.setSpacing(6)
        self.layout_infos_tchoukball.setObjectName("layout_infos_tchoukball")
        self.label_team_tchoukball = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_team_tchoukball.setFont(font)
        self.label_team_tchoukball.setObjectName("label_team_tchoukball")
        self.layout_infos_tchoukball.addWidget(self.label_team_tchoukball, 0, 0, 1, 1)
        self.label_score_tchoukball = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_score_tchoukball.setFont(font)
        self.label_score_tchoukball.setObjectName("label_score_tchoukball")
        self.layout_infos_tchoukball.addWidget(self.label_score_tchoukball, 2, 0, 1, 1)
        self.name_team_tchoukball = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_team_tchoukball.setFont(font)
        self.name_team_tchoukball.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_team_tchoukball.setObjectName("name_team_tchoukball")
        self.layout_infos_tchoukball.addWidget(self.name_team_tchoukball, 0, 1, 1, 1)
        self.nb_points_tchoukball = QtWidgets.QLabel(self.layout_main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.nb_points_tchoukball.setFont(font)
        self.nb_points_tchoukball.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nb_points_tchoukball.setObjectName("nb_points_tchoukball")
        self.layout_infos_tchoukball.addWidget(self.nb_points_tchoukball, 2, 1, 1, 1)
        self.layout_tchoukball.addLayout(self.layout_infos_tchoukball)
        self.gridLayout.addLayout(self.layout_tchoukball, 4, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 1, 0, 1, 5)
        self.line.raise_()
        self.line_2.raise_()
        self.label_ski_2.raise_()
        MainWindow.setCentralWidget(self.layout_main)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_gym.setText(_translate("MainWindow", "GYM"))
        self.label_time_gym.setText(_translate("MainWindow", "-.--.--"))
        self.label_team_gym.setText(_translate("MainWindow", "Equipe"))
        self.label_score_gym.setText(_translate("MainWindow", "Score"))
        self.name_team_gym.setText(_translate("MainWindow", "team"))
        self.nb_points_gym.setText(_translate("MainWindow", "0"))
        self.label_ski_2.setText(_translate("MainWindow", "SPONSORS"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.label_6.setText(_translate("MainWindow", ":"))
        self.label_ski.setText(_translate("MainWindow", "SKI"))
        self.label_time_ski.setText(_translate("MainWindow", "-.--.--"))
        self.label_team_ski.setText(_translate("MainWindow", "Equipe"))
        self.label_score_ski.setText(_translate("MainWindow", "Score"))
        self.name_team_ski.setText(_translate("MainWindow", "team"))
        self.nb_points_ski.setText(_translate("MainWindow", "0"))
        self.label_tchoukball.setText(_translate("MainWindow", "TCHOUKBALL"))
        self.label_time_tchoukball.setText(_translate("MainWindow", "-.--.--"))
        self.label_team_tchoukball.setText(_translate("MainWindow", "Equipe"))
        self.label_score_tchoukball.setText(_translate("MainWindow", "Score"))
        self.name_team_tchoukball.setText(_translate("MainWindow", "team"))
        self.nb_points_tchoukball.setText(_translate("MainWindow", "0"))


